#!/bin/bash
cd ~/scaletest/
source coinlist
count=0
args="$@"

while [ "x${coinlist[count]}" != "x" ]
do
  all=${coinlist[count]}
  name=${all%% *}
  if [ "$name" != "" ]
    then
     echo $name 
     komodo-cli -ac_name=$name $args
  fi
  count=$(( $count +1 ))
done
