#!/bin/bash
numchains=$1
chainname=$2
numcoins=$3
numacreward=$4

if [ -z ${1+x} ] || [ -z ${2+x} ] || [ -z ${3+x} ]
then 
    echo
    echo "Usage: ./genacs <numchains> <chainname> <supply> <acreward>"
    echo "Example: ./genacs 4096 TXSCL 77000000 100000000"
    echo
    exit
fi

startdir=$PWD
manychainsout=manychains
ufwenablefile=acufwenable
ufwdisablefile=acufwdisable
coinlistfile=coinlist
acfile=startacs
genfile=startacsgen
seedipfile=seedip

cd ~/komodo/src
git pull
gcc -o manychains komodo_port.c
./manychains -gen $numchains $chainname 0 $numcoins $numacreward > $startdir/$manychainsout

cd $startdir

echo "coinlist=(" > $coinlistfile
echo "#!/bin/bash" > $acfile
echo "cd ~/komodo/src" >> $acfile
echo "#!/bin/bash" > $genfile
echo "cd ~/komodo/src" >> $genfile

while read komodo acname acsupply acend acreward achalving acdecay amp pound portlabel port
do
    acnameonly=$(echo $acname | sed 's/-ac_name=//')
    acsupplyonly=$(echo $acsupply | sed 's/-ac_supply=//')
    let "p2pport = $port - 1"

    echo "'$acnameonly $acsupplyonly'" >> $coinlistfile
    echo "sudo ufw allow $p2pport comment '$acnameonly'" >> $ufwenablefile
    echo "sudo ufw delete allow $p2pport" >> $ufwdisablefile
    echo $acnameonly
done < "$manychainsout"

echo ")" >> $coinlistfile

myip=`curl -s4 checkip.amazonaws.com`
echo "seed_ip=$myip" > $seedipfile

rm $manychainsout
chmod +x $ufwenablefile
chmod +x $ufwdisablefile

if [ -f $ufwenablefile ] && [ -f $ufwdisablefile ] && [ -f $seedipfile ] && [ -f $coinlistfile ]
then
    echo "Success!"
else
    echo "One or more files failed to generate"
fi
