#!/bin/bash
pkill -15 iguana
rm -f ../agents/iguana *.o
git pull
cd secp256k1; ./m_unix; cd ..
cd ../crypto777; ./m_LP; cd ../iguana
clang -g -Wno-deprecated -c -O2 -DISNOTARYNODE=1 -DLIQUIDITY_PROVIDER=1 *.c ../basilisk/basilisk.c ../gecko/gecko.c ../datachain/datachain.c
clang -g  -Wno-deprecated -c -DISNOTARYNODE=1 -DLIQUIDITY_PROVIDER=1  main.c iguana777.c iguana_bundles.c ../basilisk/basilisk.c
clang -g -o ../agents/iguana *.o ../agents/libcrypto777.a -lnanomsg -lcurl -lssl -lcrypto -lpthread -lz -lm

#download scale array and start iguana
wget -qO testnet https://raw.githubusercontent.com//blackjok3rtt/scaletest/4096/scale.json
../agents/iguana scale & #> iguana.log 2> error.log  &
myip=`curl -s4 checkip.amazonaws.com`
source ~/scaletest/pubkey.txt
source ~/scaletest/seedip.txt
sleep 4
curl --url "http://127.0.0.1:7776" --data "{\"agent\":\"SuperNET\",\"method\":\"myipaddr\",\"ipaddr\":\"$myip\"}"
sleep 3

#add coins
COINS_7776/btc_7776
COINS_7776/kmd_7776
./wp_7776
./coins_7776

#Add notaries
curl --url "http://127.0.0.1:7776" --data "{\"agent\":\"iguana\",\"method\":\"addnotary\",\"ipaddr\":\"$seedip\"}"

sleep 90

#start coins
./startdpow
