#!/bin/bash
#cd ~/scaletest

chainstart=$1
chainend=$2
coinlist2file=coins_7776
dpowfile=startdpow

if [[ -z ${2+x} && ! -z ${1+x} ]]
then
    echo
    echo "setchains with no parameters will set you to work with all coins in the master list, otherwise you can set a range of chains to work with:"
    echo
    echo "Usage: ./setchains <chainfrom> <chainto>"
    echo "Example: ./setchains 0 99"
    echo
    exit
fi

if [[ ! -z ${1+x} ]]
then
   count=chainstart
else
    count=0
fi

source coinlist
rm $coinlist2file
echo "#!/bin/bash" > $dpowfile
echo "source pubkey.txt" >> $dpowfile

while [[ (! -z ${2+x} && $count -le $chainend) || (-z ${2+x} && $count -le ${#coinlist[@]}) ]]
do
    all=${coinlist[count]}
    name=${all%% *}
    if [ "$name" != "" ]
    then
       coin7776="COINS_7776/"
       coin7776+=$name
       coin7776+="_7776"
       echo $coin7776 >> $coinlist2file
       #Make dPow file
       dpow='curl --url "http://127.0.0.1:7776" --data "{\"timeout\":60000,\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"'
       dpow+=$name
       dpow+='\",\"pubkey\":\"$pubkey\"}"'
       echo $dpow >> $dpowfile
    fi
    count=$(( $count +1 ))
done

chmod +x $coinlist2file
chmod +x $dpowfile
