#!/bin/bash
source pubkey.txt
source seedip
source coinlist
count=0
delay=1
while [ "x${coinlist[count]}" != "x" ]
do
  all=${coinlist[count]}
  name=${all%% *}
  supply=`expr "$all" : '.* \(.*\)'`
  if [ "$name" != "" ]
    then
     ~/komodo/src/komodod -pubkey=$pubkey -ac_name=$name -ac_supply=$supply -addnode=$seed_ip -gen -blockprioritysize=0 &
     sleep $delay
    fi
  count=$(( $count +1 ))
done
