#!/bin/bash
cd ~/scaletest/
source coinlist2
count=0

while [ "x${coinlist2[count]}" != "x" ]
do
  all=${coinlist2[count]}
  name=${all%% *}
  if [ "$name" != "" ]
    then
     echo $name 
     ~/komodo/src/komodo-cli -ac_name=$name setgenerate true 2
     sleep 45
     ~/komodo/src/komodo-cli -ac_name=$name setgenerate false
  fi
  count=$(( $count +1 ))
done
