#!/bin/bash
source pubkey.txt
source seedip
source coinlist2
count=0
delay=1
while [[ $count -lt ${#coinlist2[@]} ]]
do
  all=${coinlist2[count]}
  name=${all%% *}
  supply=`expr "$all" : '.* \(.*\)'`
  if [ "$name" != "" ]
    then
     ~/komodo/src/komodod -pubkey=$pubkey -ac_cc=1 -ac_name=$name -ac_supply=$supply -ac_reward=100000000 -addnode=$seed_ip -gen  &
     sleep $delay
    fi
  count=$(( $count +1 ))
done
