#!/bin/bash
delay=1

source seedip
source coinlist2
source pubkey.txt
count=0
while [[ $count -le ${#coinlist2[@]} ]]
do
  all=${coinlist2[count]}
  name=${all%% *}
  supply=`expr "$all" : '.* \(.*\)'`
  if [ "$name" != "" ]
    then
     ~/komodo/src/komodod -pubkey=$pubkey -addnode=$seed_ip -ac_cc=1 -ac_name=$name -ac_supply=$supply -ac_reward=100000000 $1 &
     sleep $delay
  fi
  count=$(( $count +1 ))
done
