#!/bin/bash
cd ~/scaletest/
source coinlist2
count=0

while [[ $count -lt ${#coinlist2[@]} ]]
do
  all=${coinlist2[count]}
  name=${all%% *}
  if [ "$name" != "" ]
    then
       ~/komodo/src/komodo-cli -ac_name=$name $1 $2 $3 $4 $5 $6 $7 $8 $9 &
  fi
  count=$(( $count +1 ))
done
