#!/bin/bash
source passphrase
./marketmaker "{\"gui\":\"nogui\",\"client\":1, \"userhome\":\"/${HOME#"/"}\", \"passphrase\":\"$passphrase\", \"coins\":[{\"coin\":\"TXSCL\",\"asset\":\"TXSCL\",\"rpcport\":27970}],\"rpcport\":7000}" &
