#!/bin/bash
source passphrase
export coins="[{\"coin\":\"TXSCL\",\"asset\":\"TXSCL\",\"rpcport\":11821}]"
./stop
#git pull;
#cp ../exchanges/updateprices .;./updateprices
cd ..; 
#./m_mm;
pkill -15 marketmaker; 
./marketmaker "{\"gui\":\"nogui\",\"client\":1, \"userhome\":\"/${HOME#"/"}\", \"passphrase\":\"$passphrase\", \"coins\":$coins}" &

