#!/bin/bash
#Clean dir of old files
rm amount.txt calcaddress.txt password Radd.txt rpcports TXids
#Generate password add it to password file
password=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 20 | head -n 1)
echo "password=$password" > password

#Use Calcaddress from marketmaker to generate address from the password
calcaddress=$(./calcaddress)
  if [ "$calcaddress" != "" ]
    then
      echo $calcaddress > calcaddress.txt
    else 
       echo "Make sure MarketMaker is running"
       exit; 
    fi
Radd="Radd="
Radd+=$(grep -Po '"coinaddr":.*?[^\\]"' calcaddress.txt | awk -F':' '{print $2}')

echo $Radd > Radd.txt

#Generates 1 UTXO to the address created above for each chain and generates a new rpc port for marketmaker and saves the TXid in an array.
./fundRadd2.sh 60

#Use the list of txid's to call txblast API for each chain. 
