#!/bin/bash
magicfile=../magic
echo 'coins=(' > coins
count=0

while read acname ports magic uknum acsupply ukword
do
    acnameonly=$(echo $acname | sed 's/://')
    thisconf=$(<~/.komodo/$acnameonly/$acnameonly.conf)
    rpcport=$(echo $thisconf | grep -Po "rpcport=(\S*)" | sed 's/rpcport=//')
    echo "'[{\\\"coin\\\":\\\"$acnameonly\\\",\\\"asset\\\":\\\"$acnameonly\\\",\\\"rpcport\\\":$rpcport}]'" >>  coins
    count=$(( count +1 ))
done < "$magicfile"

echo ")" >> coins
