#!/bin/bash
#Read rpcports array and launch a marketmaker for each chain.
source passphrase
source coins
source rpcports
count=0

while [ "x${rpcports[count]}" != "x" ]
do
  rpcport=${rpcports[count]}
  ./marketmaker "{\"gui\":\"nogui\",\"client\":1, \"userhome\":\"/${HOME#"/"}\", \"passphrase\":\"$passphrase\", \"coins\":$coins, \"rpcport\":$rpcport}" &
  count=$(( $count +1 ))
done
