#!/bin/bash
source ../coinlist count=0 while [ "x${coinlist[count]}" != "x" ] do
    all=${coinlist[count]}
    name=${all%% *}
    if [ "$name" != "" ]
    then
        echo "blocknotify=node /home/pool/z-nomp/scripts/cli.js blocknotify $name %s" >> ~/.komodo/$name/$name.conf
    fi
    count=$(( $count +1 ))
done
