#!/bin/bash
walletaddress=RKeiPCKxMqoqvjji6wAXPJrbE3KAkijhuN

magicfile=../magic
coinsdir=./coins
poolconfigdir=./pool_configs
coinstpl=coins.template
pooltpl=poolconfigs.template
ufwenablefile=stratufwenable
ufwdisablefile=stratufwdisable

stratumport=20777

cointemplate=$(<$coinstpl)
pooltemplate=$(<$pooltpl)

mkdir -p $coinsdir
mkdir -p $poolconfigdir

#clean old up
rm $ufwenablefile
rm $ufwdisablefile

while read acname ports magic uknum acsupply ukword
do
    acnameonly=$(echo $acname | sed 's/://')
    #magic=$(echo $magic | sed 's/magic.//')
    #magicrev=""
    #for((i=0;i<=${#magic};i+=2)); do
    #    magicrev="${magic:i:2}$magicrev"
    #done

    p2pport=$(echo $ports | egrep -o '[[:digit:]]{4,5}' | head -n1)

    thisconf=$(<~/.komodo/$acnameonly/$acnameonly.conf)

    rpcuser=$(echo $thisconf | grep -Po "rpcuser=(\S*)" | sed 's/rpcuser=//')
    rpcpass=$(echo $thisconf | grep -Po "rpcpassword=(\S*)" | sed 's/rpcpassword=//')
    rpcport=$(echo $thisconf | grep -Po "rpcport=(\S*)" | sed 's/rpcport=//')

    #let "p2pport = $port - 1"

    echo "$cointemplate" | sed "s/COINNAMEVAR/$acnameonly/" | sed "s/MAGICREVVAR/$magicrev/" > $coinsdir/$acnameonly.json
    echo "$pooltemplate" | sed "s/COINNAMEVAR/$acnameonly/" | sed "s/WALLETADDRVAR/$walletaddress/" | sed "s/STRATUMPORTVAR/$stratumport/" | sed "s/RPCPORTVAR/$rpcport/" | sed "s/RPCUSERVAR/$rpcuser/" | sed "s/RPCPASSVAR/$rpcpass/" > $poolconfigdir/$acnameonly.json

    echo "sudo ufw allow $stratumport comment 'Stratum $acnameonly'" >> $ufwenablefile
    echo "sudo ufw delete allow $stratumport" >> $ufwdisablefile

    let "stratumport = $stratumport + 1"
done < "$magicfile"

chmod +x $ufwenablefile
chmod +x $ufwdisablefile
