#!/bin/bash
magicfile=../magic
coins='export coins="['
rm enable
while read acname ports magic uknum acsupply ukword
do
    acnameonly=$(echo $acname | sed 's/://')
    thisconf=$(<~/.komodo/$acnameonly/$acnameonly.conf)
    rpcport=$(echo $thisconf | grep -Po "rpcport=(\S*)" | sed 's/rpcport=//')
    enable='curl --url "http://127.0.0.1:7783" --data "{\"userpass\":\"$userpass\",\"method\":\"enable\",\"coin\"'
    enable+=":\\\"$acnameonly\\\"}"
    echo $enable >> enable
    coins+="{\\\"coin\\\":\\\"$acnameonly\\\",\\\"asset\\\":\\\"$acnameonly\\\",\\\"rpcport\\\":$rpcport}, "
done < "$magicfile"
coins=${coins:0:-2}
coins+=']"'
echo $coins > coins
chmod +x enable
